version: "3"
services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
